version: '3'

volumes:
  postgres_data: {}
  pgadmin: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: abacum_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres

  pgadmin:
    container_name: abacum_pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "fabian.falon@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

